server:
  port: 8080

spring:
  datasource:
    driver-class-name: ${DRIVER_CLASS_NAME}
    username: ${USER_NAME}
    url: ${DATASOURCE_URL}
    password: ${DATASOURCE_PASSWORD}
    hikari:
      maximum-pool-size: 20

  jpa:
    database: ${JPA_DATABASE}
    database-platform: ${DATABASE_PLATFORM}
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  redis:
    host: localhost
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}

mail:
  address:
    admin: ${MAIL_ADDRESS_ADMIN}

cloud:
  aws:
    credentials:
      accessKey: ${BE_AWS_ACCESS_KEY}
      secretKey: ${BE_AWS_SECRET_ACCESS_KEY}
    s3:
      bucket: ${IMAGE_S3_BUCKET}
    region:
      static: ap-northeast-2
    stack:
      auto: 'false'

jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: ${ACCESS_TOKEN_EXPIRATION_MINUTES}
  refresh-token-expiration-minutes: ${REFRESH_TOKEN_EXPIRATION_MINUTES}

kafka:
  topic: ${KAFKA_TOPIC}
  id: ${KAFKA_ID}
  broker: ${KAFKA_BROKER}