server:
  port: 8080

spring:
  datasource:
    driver-class-name: ${{ secrets.DRIVER_CLASS_NAME }}
    username: ${{ secrets.USER_NAME }}
    url: ${{ secrets.DATASOURCE_URL }}
    password: ${{ secrets.DATASOURCE_PASSWORD }}
    hikari:
      maximum-pool-size: 20

  jpa:
    database: ${{ secrets.JPA_DATABASE }}
    database-platform: ${{ secrets.DATABASE_PLATFORM }}
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  redis:
    host: localhost
    port: ${{ secrets.REDIS_PORT }}
    password: ${{ secrets.REDIS_PASSWORD }}

mail:
  address:
    admin: ${{ secrets.MAIL_ADDRESS_ADMIN }}

cloud:
  aws:
    credentials:
      accessKey: ${{ secrets.BE_AWS_ACCESS_KEY }}
      secretKey: ${{ secrets.BE_AWS_SECRET_ACCESS_KEY }}
    s3:
      bucket: ${{ secrets.IMAGE_S3_BUCKET }}
    region:
      static: ap-northeast-2
    stack:
      auto: 'false'

jwt:
  key: ${{ secrets.JWT_SECRET_KEY }}
  access-token-expiration-minutes: ${{ secrets.ACCESS_TOKEN_EXPIRATION_MINUTES }}
  refresh-token-expiration-minutes: ${{ secrets.REFRESH_TOKEN_EXPIRATION_MINUTES }}

kafka:
  topic: ${{ secrets.KAFKA_TOPIC }}
  id: ${{ secrets.KAFKA_ID }}
  broker: ${{ secrets.KAFKA_BROKER }}
